# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classcode', models.CharField(max_length=10)),
                ('coursecode', models.CharField(max_length=10)),
                ('coursetitle', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('stat', models.CharField(max_length=10)),
                ('instructors', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=30)),
                ('room', models.CharField(max_length=10)),
                ('compredate', models.CharField(max_length=20)),
            ],
        ),
    ]
